In [1]:
#Notebook to Show the Preprocess and Labeling Steps!
#Dataset is split into Cars and NoCars so Labeling will be based on that!

In [2]:
import numpy as np
import pandas as pd 
import os
import time


In [3]:
import cv2
from PIL import Image
import tensorflow as tf
from random import randrange
import pickle
import json

In [4]:
print(os.listdir(os.getcwd()))

['AlexNet_Keras.ipynb', 'Car_Sample', 'NoCar_Sample', 'Process_AND_Label.ipynb', 'sample_test_data.pkl', 'sample_train_data.pkl', 'Test', 'Train']


In [5]:
#I:\WPI\Fall 2020\Computer Vision - RBE 549\CV Project\AlexNet_Implementation\Car_Sample\Train

In [6]:
#Extracting all training images for car - Trial
# train_car_path = "\\".join((car_path, "train"))
# train_car_dir = os.listdir(train_car_path)
# train_img = []
# train_path = train_car_path
# img_dir = train_car_dir
# for img_name in img_dir:
#     img_path = "\\".join((train_path, img_name))
#     #print("Path: ", img_path)
#     img_grey = np.array(Image.open(img_path).convert('LA'))
#     img_grey = tf.image.resize(img_grey, (256,256),preserve_aspect_ratio=False).numpy()
#     #(print())
#     train_img.append([1, img_grey[:, :, 0]])
# print(train_img[1][1])
# train_car_img = np.array(train_img)

In [7]:
#Extracting all car images for 
def extract_resize_img(folder_path, dataset_type, label_name):
    """
    Extract images in grayscale and resize them. 
    Return back the extracted images with associated label.
    """
    dataset_path = "\\".join((folder_path, dataset_type))
    img_dir = os.listdir(dataset_path)
    img_data = []
    for img_name in img_dir:
        img_path = "\\".join((dataset_path, img_name))
        #print("Path: ", img_path)
        img_grey = np.array(Image.open(img_path).convert('LA'))
        img_grey = tf.image.resize(img_grey, (256, 256), preserve_aspect_ratio=False).numpy()
        #img_grey = img_grey.reshape(256, 256, 1)
        #img_data.append([img_grey[:, :, 0]])

        img_data.append([img_grey[:, :, 0]])

    return(np.array(img_data))



In [8]:
def random_shuffle(img, label = 1):
    label_mtx = label* np.shape(img)[0]
    permutation = np.random.permutation(np.shape(label))
    img = img[permutation]
    label = img[permutation]

In [9]:
folder_path = os.getcwd()
car_path = "\\".join((folder_path, "Car_Sample"))
noise_path = "\\".join((folder_path, "NoCar_Sample"))

In [10]:
#Worked!
#Split up the extraction process if it take too much time!
start_time = time.time()
car_img_train = extract_resize_img(folder_path = car_path, dataset_type = 'train', label_name = 1)
car_img_train = car_img_train.reshape(car_img_train.shape[0], 256, 256, 1)

car_img_test = extract_resize_img(folder_path = car_path, dataset_type = 'test', label_name = 1)
car_img_test = car_img_test.reshape(car_img_test.shape[0], 256, 256, 1)

noise_img_train = extract_resize_img(folder_path = noise_path, dataset_type = 'train', label_name = 0)
noise_img_train = noise_img_train.reshape(noise_img_train.shape[0], 256, 256, 1)

noise_img_test = extract_resize_img(folder_path = noise_path, dataset_type = 'test', label_name = 0)
noise_img_test = noise_img_test.reshape(noise_img_test.shape[0], 256, 256, 1)

print("Time Taken: ", time.time() - start_time)

Time Taken:  3.4842419624328613


In [17]:
label_car_train = [1] * car_img_train.shape[0]
label_noise_train = [0] * noise_img_train.shape[0]
train_img = np.concatenate([car_img_train, noise_img_train])
train_label = np.concatenate([label_car_train, label_noise_train])

permute_train = np.random.permutation(len(train_label))

train_img   = train_img[permute_train]
train_label = train_label[permute_train]

In [18]:
label_car_test= [1] * car_img_test.shape[0]
label_noise_test = [0] * noise_img_test.shape[0]
test_img = np.concatenate([car_img_test, noise_img_test])
test_label = np.concatenate([label_car_test, label_noise_test])

permute_test = np.random.permutation(len(test_label))

test_img   = train_img[permute_test]
test_label = train_label[permute_test]


In [19]:
test_label

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1])

In [110]:
# label_car_train = [1] * np.shape(car_img_train)[0]
# print(label_car_train)
# # np.shape(label_car)
# # np.shape(car_img_train)[0]
# # permutation = np.random.permutation(np.shape(car_img_train)[0])
# #car_img_train[:, 1] = car_img_train.reshape(car_img_train.shape[0], 256, 256, 1)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [105]:
# #print(car_img_train.shape)
# #print((car_img_train[1]))
# car_img_train = car_img_train.reshape(car_img_train.shape[0], 256, 256, 1)
# print(car_img_train.shape)

(90, 256, 256, 1)


In [73]:
# train_data = np.concatenate([car_img_train, noise_img_train])
# np.random.shuffle(train_data)
# test_data = np.concatenate([car_img_test, noise_img_test])
# np.random.shuffle(test_data)

In [74]:
# print("Train: ", np.shape(train_data))
# print("Test: ", np.shape(test_data))

Train:  (180, 2)
Test:  (20, 2)


In [21]:
print("Train Img: ", np.shape(train_img))
print("Test Img: ", np.shape(test_img))


print("Train Label: ", np.shape(train_label))
print("Test Label: ", np.shape(test_label))

Train Img:  (180, 256, 256, 1)
Test Img:  (20, 256, 256, 1)
Train Label:  (180,)
Test Label:  (20,)


In [23]:
#Testing!

print("Train Label:", train_label[1])
print("Train Img:\n", np.shape(train_img[1]))
print("\n\n")
print("Test Label:", test_label[1])
print("Test Img:\n", np.shape(test_img[1]))

Train Label: 0
Train Img:
 (256, 256, 1)



Test Label: 1
Test Img:
 (256, 256, 1)


In [76]:
#Check if shuffle maintains the data integrity!
arr = np.arange(9).reshape((3,3))
print(arr)
np.random.shuffle(arr)
print(arr) #Checked!

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [25]:
with open("sample_train_img.pkl", "wb") as f_name:
    pickle.dump(train_img, f_name)

with open("sample_train_label.pkl", "wb") as f_name:
    pickle.dump(train_label, f_name)

In [26]:
with open("sample_test_img.pkl", "wb") as f_name:
    pickle.dump(test_img, f_name)

with open("sample_test_label.pkl", "wb") as f_name:
    pickle.dump(test_label, f_name)

In [27]:
with open("sample_test_img.pkl", "rb") as f_name:
    train_sample = pickle.load(f_name)
   

In [29]:
with open("sample_train_label.pkl", "rb") as f_name:
    train_label_sample = pickle.load(f_name)
   